name: hf-model
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - appnope=0.1.2
  - arrow-cpp=8.0.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=22.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - blosc=1.21.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - cmake=3.22.1
  - comm=0.1.2
  - cryptography=38.0.4
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - datasets=2.8.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - dill=0.3.6
  - distro=1.5.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3
  - fftw=3.3.9
  - filelock=3.9.0
  - flit-core=3.6.0
  - freetype=2.10.4
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - gmp=6.2.1
  - gnutls=3.6.5
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - huggingface_hub=0.11.1
  - icu=70.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.7.0
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jxrlib=1.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.14
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.3
  - make=4.2.1
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.4
  - multiprocess=0.70.14
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.4.1
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - orc=1.7.4
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - protobuf=3.20.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=8.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-xxhash=3.2.0
  - python_abi=3.8
  - pytorch=1.13.1
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rhash=1.4.1
  - rsa=4.7.2
  - sacremoses=master
  - scikit-build=0.15.0
  - scikit-image=0.19.3
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - tokenizers=0.13.0.dev0
  - toolz=0.12.0
  - torchvision=0.14.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - transformers=4.25.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.13
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xxhash=0.8.1
  - xz=5.2.8
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - evaluate==0.4.0
      - opencv-python-headless==4.4.0.44
      - qudida==0.0.4
      - responses==0.18.0
